-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Sobel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_mat_rows_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_mat_cols_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_mat_data_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_src_mat_data_V_ce0 : OUT STD_LOGIC;
    p_src_mat_data_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_dst_matx_data_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_dst_matx_data_V_ce0 : OUT STD_LOGIC;
    p_dst_matx_data_V_we0 : OUT STD_LOGIC;
    p_dst_matx_data_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_maty_data_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_dst_maty_data_V_ce0 : OUT STD_LOGIC;
    p_dst_maty_data_V_we0 : OUT STD_LOGIC;
    p_dst_maty_data_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of Sobel is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal width_fu_38_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal width_reg_48 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_fu_43_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_reg_53 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_xFSobelFilter3x3_fu_26_ap_start : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_ap_done : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_ap_idle : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_ap_ready : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_ce0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_ce0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_we0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_ce0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_we0 : STD_LOGIC;
    signal grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFSobelFilter3x3_fu_26_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component xFSobelFilter3x3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_mat_data_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_src_mat_data_V_ce0 : OUT STD_LOGIC;
        p_src_mat_data_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_dst_matx_data_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_dst_matx_data_V_ce0 : OUT STD_LOGIC;
        p_dst_matx_data_V_we0 : OUT STD_LOGIC;
        p_dst_matx_data_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_maty_data_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_dst_maty_data_V_ce0 : OUT STD_LOGIC;
        p_dst_maty_data_V_we0 : OUT STD_LOGIC;
        p_dst_maty_data_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_height : IN STD_LOGIC_VECTOR (15 downto 0);
        img_width : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_xFSobelFilter3x3_fu_26 : component xFSobelFilter3x3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFSobelFilter3x3_fu_26_ap_start,
        ap_done => grp_xFSobelFilter3x3_fu_26_ap_done,
        ap_idle => grp_xFSobelFilter3x3_fu_26_ap_idle,
        ap_ready => grp_xFSobelFilter3x3_fu_26_ap_ready,
        p_src_mat_data_V_address0 => grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_address0,
        p_src_mat_data_V_ce0 => grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_ce0,
        p_src_mat_data_V_q0 => p_src_mat_data_V_q0,
        p_dst_matx_data_V_address0 => grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_address0,
        p_dst_matx_data_V_ce0 => grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_ce0,
        p_dst_matx_data_V_we0 => grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_we0,
        p_dst_matx_data_V_d0 => grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_d0,
        p_dst_maty_data_V_address0 => grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_address0,
        p_dst_maty_data_V_ce0 => grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_ce0,
        p_dst_maty_data_V_we0 => grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_we0,
        p_dst_maty_data_V_d0 => grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_d0,
        img_height => height_reg_53,
        img_width => width_reg_48);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_xFSobelFilter3x3_fu_26_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFSobelFilter3x3_fu_26_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_xFSobelFilter3x3_fu_26_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFSobelFilter3x3_fu_26_ap_ready = ap_const_logic_1)) then 
                    grp_xFSobelFilter3x3_fu_26_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                height_reg_53 <= height_fu_43_p1;
                width_reg_48 <= width_fu_38_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_xFSobelFilter3x3_fu_26_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_xFSobelFilter3x3_fu_26_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_xFSobelFilter3x3_fu_26_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_xFSobelFilter3x3_fu_26_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_xFSobelFilter3x3_fu_26_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_xFSobelFilter3x3_fu_26_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_xFSobelFilter3x3_fu_26_ap_start <= grp_xFSobelFilter3x3_fu_26_ap_start_reg;
    height_fu_43_p1 <= p_src_mat_rows_read(16 - 1 downto 0);
    p_dst_matx_data_V_address0 <= grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_address0;
    p_dst_matx_data_V_ce0 <= grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_ce0;
    p_dst_matx_data_V_d0 <= grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_d0;
    p_dst_matx_data_V_we0 <= grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_we0;
    p_dst_maty_data_V_address0 <= grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_address0;
    p_dst_maty_data_V_ce0 <= grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_ce0;
    p_dst_maty_data_V_d0 <= grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_d0;
    p_dst_maty_data_V_we0 <= grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_we0;
    p_src_mat_data_V_address0 <= grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_address0;
    p_src_mat_data_V_ce0 <= grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_ce0;
    width_fu_38_p1 <= p_src_mat_cols_read(16 - 1 downto 0);
end behav;
