// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Sobel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_mat_rows_read,
        p_src_mat_cols_read,
        p_src_mat_data_V_address0,
        p_src_mat_data_V_ce0,
        p_src_mat_data_V_q0,
        p_dst_matx_data_V_address0,
        p_dst_matx_data_V_ce0,
        p_dst_matx_data_V_we0,
        p_dst_matx_data_V_d0,
        p_dst_maty_data_V_address0,
        p_dst_maty_data_V_ce0,
        p_dst_maty_data_V_we0,
        p_dst_maty_data_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_mat_rows_read;
input  [31:0] p_src_mat_cols_read;
output  [11:0] p_src_mat_data_V_address0;
output   p_src_mat_data_V_ce0;
input  [7:0] p_src_mat_data_V_q0;
output  [11:0] p_dst_matx_data_V_address0;
output   p_dst_matx_data_V_ce0;
output   p_dst_matx_data_V_we0;
output  [7:0] p_dst_matx_data_V_d0;
output  [11:0] p_dst_maty_data_V_address0;
output   p_dst_maty_data_V_ce0;
output   p_dst_maty_data_V_we0;
output  [7:0] p_dst_maty_data_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] width_fu_38_p1;
reg   [15:0] width_reg_48;
wire   [15:0] height_fu_43_p1;
reg   [15:0] height_reg_53;
wire    grp_xFSobelFilter3x3_fu_26_ap_start;
wire    grp_xFSobelFilter3x3_fu_26_ap_done;
wire    grp_xFSobelFilter3x3_fu_26_ap_idle;
wire    grp_xFSobelFilter3x3_fu_26_ap_ready;
wire   [11:0] grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_address0;
wire    grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_ce0;
wire   [11:0] grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_address0;
wire    grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_ce0;
wire    grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_we0;
wire   [7:0] grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_d0;
wire   [11:0] grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_address0;
wire    grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_ce0;
wire    grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_we0;
wire   [7:0] grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_d0;
reg    grp_xFSobelFilter3x3_fu_26_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_xFSobelFilter3x3_fu_26_ap_start_reg = 1'b0;
end

xFSobelFilter3x3 grp_xFSobelFilter3x3_fu_26(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_fu_26_ap_start),
    .ap_done(grp_xFSobelFilter3x3_fu_26_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_fu_26_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_fu_26_ap_ready),
    .p_src_mat_data_V_address0(grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_address0),
    .p_src_mat_data_V_ce0(grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_ce0),
    .p_src_mat_data_V_q0(p_src_mat_data_V_q0),
    .p_dst_matx_data_V_address0(grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_address0),
    .p_dst_matx_data_V_ce0(grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_ce0),
    .p_dst_matx_data_V_we0(grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_we0),
    .p_dst_matx_data_V_d0(grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_d0),
    .p_dst_maty_data_V_address0(grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_address0),
    .p_dst_maty_data_V_ce0(grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_ce0),
    .p_dst_maty_data_V_we0(grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_we0),
    .p_dst_maty_data_V_d0(grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_d0),
    .img_height(height_reg_53),
    .img_width(width_reg_48)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_fu_26_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFSobelFilter3x3_fu_26_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_fu_26_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_fu_26_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_reg_53 <= height_fu_43_p1;
        width_reg_48 <= width_fu_38_p1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_xFSobelFilter3x3_fu_26_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFSobelFilter3x3_fu_26_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFSobelFilter3x3_fu_26_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_xFSobelFilter3x3_fu_26_ap_start = grp_xFSobelFilter3x3_fu_26_ap_start_reg;

assign height_fu_43_p1 = p_src_mat_rows_read[15:0];

assign p_dst_matx_data_V_address0 = grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_address0;

assign p_dst_matx_data_V_ce0 = grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_ce0;

assign p_dst_matx_data_V_d0 = grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_d0;

assign p_dst_matx_data_V_we0 = grp_xFSobelFilter3x3_fu_26_p_dst_matx_data_V_we0;

assign p_dst_maty_data_V_address0 = grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_address0;

assign p_dst_maty_data_V_ce0 = grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_ce0;

assign p_dst_maty_data_V_d0 = grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_d0;

assign p_dst_maty_data_V_we0 = grp_xFSobelFilter3x3_fu_26_p_dst_maty_data_V_we0;

assign p_src_mat_data_V_address0 = grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_address0;

assign p_src_mat_data_V_ce0 = grp_xFSobelFilter3x3_fu_26_p_src_mat_data_V_ce0;

assign width_fu_38_p1 = p_src_mat_cols_read[15:0];

endmodule //Sobel
